services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: assistant_backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: assistant_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
